on:
    release:
        types: [created]

jobs:
    release:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: "macos-latest"
                      args: "--target aarch64-apple-darwin"
                    - platform: "macos-latest"
                      args: "--target x86_64-apple-darwin"
                    - platform: "ubuntu-22.04"
                      args: ""
                    - platform: "windows-latest"
                      args: ""
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@master
              with:
                  repository: flazepe/clipper
                  path: clipper

            - uses: actions/checkout@v4
              with:
                  path: clipper-gui

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-22.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            - name: install frontend dependencies
              run: cd clipper-gui && npm i

            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  projectPath: clipper-gui
                  args: ${{ matrix.args }}
                  tagName: v__VERSION__
                  releaseName: v__VERSION__
